const currentDate = () => {
    const now = new Date();
    return now.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
};

const currentTime = () => {
    const now = new Date();
    return now.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: true,
    });
};

export const EmailTemplate = (to: string, subject: string, body: string) => {
    // Convert newlines in body to <br> for HTML rendering
    const formattedBody = body
        .replace(/\n/g, '<br>')
        .replace(/•/g, '&#8226;')
        .replace(/- /g, '&#8226; ');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${subject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #0f0f1a; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
    
    <!-- Outer Container -->
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #0f0f1a; padding: 40px 20px;">
        <tr>
            <td align="center">
                
                <!-- Main Card -->
                <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width: 600px; width: 100%; border-radius: 16px; overflow: hidden; box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);">
                    
                    <!-- Hero Header -->
                    <tr>
                        <td style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 30%, #0f3460 60%, #533483 100%); padding: 48px 40px 40px; text-align: center;">
                            
                            <!-- Weather Icon -->
                            <div style="font-size: 64px; margin-bottom: 12px;">⛅</div>
                            
                            <!-- Title -->
                            <h1 style="margin: 0 0 8px; font-size: 28px; font-weight: 700; color: #ffffff; letter-spacing: -0.5px;">
                                ${subject}
                            </h1>
                            
                            <!-- Date & Time -->
                            <p style="margin: 0; font-size: 14px; color: rgba(255, 255, 255, 0.6); letter-spacing: 0.5px;">
                                ${currentDate()} &nbsp;•&nbsp; ${currentTime()}
                            </p>
                            
                            <!-- Divider Line -->
                            <div style="margin-top: 28px; height: 1px; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);"></div>
                        </td>
                    </tr>
                    
                    <!-- Weather Content Body -->
                    <tr>
                        <td style="background: linear-gradient(180deg, #16213e 0%, #1a1a2e 100%); padding: 36px 40px;">
                            
                            <!-- Greeting -->
                            <p style="margin: 0 0 24px; font-size: 15px; color: rgba(255, 255, 255, 0.7); line-height: 1.5;">
                                Hello 👋, here's your latest weather update:
                            </p>
                            
                            <!-- Weather Data Card -->
                            <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td style="background: rgba(255, 255, 255, 0.05); border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 12px; padding: 28px 24px;">
                                        <div style="font-size: 15px; color: #e0e0e0; line-height: 2; letter-spacing: 0.2px;">
                                            ${formattedBody}
                                        </div>
                                    </td>
                                </tr>
                            </table>
                            
                        </td>
                    </tr>
                    
                    <!-- Info Banner -->
                    <tr>
                        <td style="background: rgba(83, 52, 131, 0.15); padding: 20px 40px; border-top: 1px solid rgba(83, 52, 131, 0.3);">
                            <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td style="font-size: 13px; color: rgba(255, 255, 255, 0.5); line-height: 1.5;">
                                        💡 <span style="color: rgba(255, 255, 255, 0.7);">Tip:</span> This weather report was generated by your AI Weather Agent using real-time data.
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    
                    <!-- Footer -->
                    <tr>
                        <td style="background-color: #0d0d1a; padding: 32px 40px; text-align: center; border-top: 1px solid rgba(255, 255, 255, 0.05);">
                            
                            <!-- Logo / Brand -->
                            <p style="margin: 0 0 8px; font-size: 16px; font-weight: 700; color: rgba(255, 255, 255, 0.8); letter-spacing: 1px;">
                                🤖 AI Weather Agent
                            </p>
                            
                            <p style="margin: 0 0 16px; font-size: 12px; color: rgba(255, 255, 255, 0.3);">
                                Powered by OpenAI Agent SDK
                            </p>
                            
                            <!-- Divider -->
                            <div style="margin: 0 auto 16px; width: 40px; height: 2px; background: linear-gradient(90deg, #533483, #0f3460); border-radius: 1px;"></div>
                            
                            <p style="margin: 0; font-size: 11px; color: rgba(255, 255, 255, 0.25); line-height: 1.6;">
                                Sent to ${to}<br>
                                This is an automated weather report. Please do not reply to this email.
                            </p>
                        </td>
                    </tr>
                    
                </table>
                <!-- End Main Card -->
                
            </td>
        </tr>
    </table>
    <!-- End Outer Container -->
    
</body>
</html>
`;
};